### ISSUE TITLE
How to use 'ZebraNativeZpl'

### ISSUE THREAD

**Issue by JesielSNunes** [w3blogfr/zebra-zpl#10]
Hello

In this class 'ZebraTestGraphics' would it be possible to add native ZPL code ?.I am using this code below, but it is creating a blank image.

```java
zebraLabel.addElement(new ZebraNativeZpl("^xa^cfa,50^fo100,100^fdHello World^fs^xz"));
```

Thank you

**Comment by w3blogfr** [comment]
Unfortunaly,
ZebraTestGraphics is just something to have a quick dirty preview and not manage ZebraNativeZpl.
You need to print direclty on your physical printer if you want preview.

If you nativeZPL code was something I used, I would probably created a custom Java Object to hide the complexity

**Comment by JesielSNunes** [comment]
Hello w3blogfr,
[zpl-code.txt](https://github.com/w3blogfr/zebra-zpl/files/2170744/zpl-code.txt)

I need to convert this native ZPL (attached) to an image, would it be possible to do this using this library?

Thank you.

**Comment by w3blogfr** [comment]
Sorry, there is no converter in that way.

This libary is only used to go from Java Object to ZPL. 

ZebraTestGraphics is simply a tools to show where you are putting your text or barcode., but it's just by respecting coordinate(x,y), it's not reflect what will be really printed by zebra printer.
