### ISSUE TITLE
picture printing

### ISSUE THREAD

**Issue by dv996coding** [w3blogfr/zebra-zpl#15]
Hello, how does zerba achieve image printing?

**Comment by w3blogfr** [comment]
Actually, this libary do not manage image out of the box.
I enjoy you to read how you can do that with native instruction.

http://www.tracerplus.com/kb/Manuals/ZPL_Vol1.pdf
http://www.tracerplus.com/kb/Manuals/ZPL_Vol2.pdf

zebra-zpl allow you to add native command all the time.

**Comment by dv996coding** [comment]
Thank you very much, I tried to implement it
