### ISSUE TITLE
use ZebraNativeZpl

### ISSUE THREAD

**Issue by suhoKKK** [w3blogfr/zebra-zpl#16]
hello. I want to make good use of your library. I need a function to convert zpl to image in java, but I
" new ZebraText(10, 520, "Ref log:", 11) " There are limitations to writing code this way. complete zpl (ex. ^XA
^FO10,84^A0N,58,57^FDProduct:^FS
^FO395,85^A0N,58,57^FDCamera^FS 
^FO10,161^A0N,58,57^FDCA201212AA^FS) should be converted, but only a blank screen is displayed with ZebraNativeZpl. Is there any other way to use it?
I tried " new ZebraNativeZpl(" ^XA^FO10,84^A0N,58,57^FDProduct:^FS ^FO395,85^A0N,58,57^FDCamera^FS ^FO10,161^A0N,58,57^FDCA201212AA^FS^XZ"
));

**Comment by w3blogfr** [comment]
For sure, ZebraNativeZpl is the good approach as far it will let you writing the code yourself and image are not natively supported

I suggest you to try to install ZebraDesigner, and to compare the generate code.

Does your image is static or dynamic?

If static, you may can try solution to get the encoded image : https://stackoverflow.com/a/36868141/1638798

Unfortunatly, I don't have anymore a Zebra printer to test it.
