### ISSUE TITLE
Barcode code 128 subset

### ISSUE THREAD

**Issue by foameraserblue** [w3blogfr/zebra-zpl#17]
Hello, I would like to inquire about Code128.

Code128 has three subsets (subset A, subset B (default), subset C).

In the case of the ZebraBarCode128 object, only the default subset B was confirmed to be supported.

Is it okay to contribute code supporting the remaining subsets A and C?

It is related to the issue below.
https://github.com/w3blogfr/zebra-zpl/issues/8

**Comment by w3blogfr** [comment]
If you want to contribute, you're welcome. You can submit a pull request

**Comment by w3blogfr** [comment]
Hello, I release a new version, integrating some features from fork.
I also improve the inheritance, and create a fluent accessor system (instead of fluent setters).

please take a look.

**Comment by foameraserblue** [comment]
thank you. It seems like a much better structure.

And thank you for releasing the new version quickly!
