### ISSUE TITLE
Do you want to add a license for the Library?

### ISSUE THREAD

**Issue by dreizweieinsmeins** [w3blogfr/zebra-zpl#2]
Hello w3blogfr,

i want to use your Library but i dont know if i can use it because u didnt write something about the license. I'm developing at the moment on a prototyp for an RFID Java Printer Application and if i can use your library i have much less work to do.

**Comment by w3blogfr** [comment]
It's done, I choose MIT license, I hope you're enjoy and improved this library.

**Comment by dreizweieinsmeins** [comment]
Thanks!
