### ISSUE TITLE
Code 128 Barcode in zpl

### ISSUE THREAD

**Issue by somaniab** [w3blogfr/zebra-zpl#3]
I want to show code 128 barcode . right now it just shows plain text .
zebraLabel.addElement(new ZebraBarCode39(0, 200, "CA201212AA", 118, 2, 2));

I want to show barcode 128 representation in this . right now it just shows text CA201212AA . how can i do that ?

**Comment by w3blogfr** [comment]
Try something like this

`zebraLabel.addElement(new ZebraBarCode128(50, 105, "CA201212AA", 60));`

**Comment by somaniab** [comment]
Thanks for the quick response . if i use this , i get NullPointerException while creating bufferedImage out of this .
```java
 BufferedImage image = zebraLabel.getImagePreview();
```
Exception in thread "main" java.lang.NullPointerException
	at fr.w3blog.zpl.model.element.ZebraBarCode.drawPreviewGraphic(ZebraBarCode.java:177)
	at fr.w3blog.zpl.model.ZebraLabel.getImagePreview(ZebraLabel.java:212)
	at MainClass.main(MainClass.java:33)

**Comment by w3blogfr** [comment]
drawPreviewGraphic was done to have a preview in first version with
barCode39.

I didn't make yet a adaptation for barCode128.

2015-11-02 10:23 GMT+01:00 Abhishek Somani <notifications@github.com>:

> Thanks for the quick response . if i use this , i get NullPointerException
> while creating bufferedImage out of this .
>
>  BufferedImage image = zebraLabel.getImagePreview();
>
> Exception in thread "main" java.lang.NullPointerException
> at
> fr.w3blog.zpl.model.element.ZebraBarCode.drawPreviewGraphic(ZebraBarCode.java:177)
> at fr.w3blog.zpl.model.ZebraLabel.getImagePreview(ZebraLabel.java:212)
> at MainClass.main(MainClass.java:33)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3blogfr/zebra-zpl/issues/3#issuecomment-152967039>.
>



-- 
Thibaut TROPARDY

**Comment by somaniab** [comment]
Is there a way to see the image , before actually sending it to printer ? will this print barcode fine when i send to printer using ZebraUtils.printZpl method

**Comment by w3blogfr** [comment]
I could create preview method for 128 bar code, but preview is not accurate
with bar code options (test interpretation, ratio, width,etc)

Preview is just adapted to see where will be bar code and label in the
label.

2015-11-02 10:28 GMT+01:00 Abhishek Somani <notifications@github.com>:

> Is there a way to see the image , before actually sending it to printer ?
> will this print barcode fine when i send to printer using
> ZebraUtils.printZpl method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3blogfr/zebra-zpl/issues/3#issuecomment-152968527>.
>



-- 
Thibaut TROPARDY

**Comment by somaniab** [comment]
so will it print fine when i send it directly to printer ? i hope it does

**Comment by w3blogfr** [comment]
Printer will print label, but I can not guarantee bar code will have
correct size and ratio.

When I use librairie, I print some labels before to find correct options. I
scan printed label to have best scanner detection

Almost time, default ratio is best.

Another good solution is to useuse Zebra designer 2 to see best options for
a bar code (ratio).
And then add correct options to ZebraBarCode128 constructor.



2015-11-02 10:41 GMT+01:00 Abhishek Somani <notifications@github.com>:

> so will it print fine when i send it directly to printer ? i hope it does
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w3blogfr/zebra-zpl/issues/3#issuecomment-152971154>.
>



-- 
Thibaut TROPARDY

**Comment by somaniab** [comment]
ok thanks .
