### ISSUE TITLE
Helvetica Font

### ISSUE THREAD

**Issue by somaniab** [w3blogfr/zebra-zpl#4]
What is the equivalent letter or string for Helvetica font ?

**Comment by w3blogfr** [comment]
I don't know if there is an equivalent.

Default on Zebra Printer, there is font A,B,C,D, F and G, may be someone is almost the same.


if no default font is adapted, you can try these solution
I never done, and I can't help you anymore about this issue

First, you can load custom font on your printer following this link https://km.zebra.com/kb/index?page=content&id=SO7889

In theory, you can download font and bitmap using ZPL  command (DT or CF instruction)

Take a look in ZPL_Vol1.pdf page 144 http://www.tracerplus.com/kb/Manuals/ZPL_Vol1.pdf

Zebra-zpl librairie has no function for this command, however, you can use  ZebraNativeZpl object

**Comment by somaniab** [comment]
Thanks for the help .
