### ISSUE TITLE
Can not find printer name

### ISSUE THREAD

**Issue by sakitA** [w3blogfr/zebra-zpl#7]
_ZebraUtils.printZpl(String zpl, String printerName)_ does not work properly. 
```
PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
for (int i = 0; i < services.length; i++) {
        PrintServiceAttribute attr = services[i].getAttribute(PrinterName.class);
        sPrinterName = ((PrinterName) attr).getValue();
	if (sPrinterName.toLowerCase().indexOf(printerName) >= 0) {
	       psZebra = services[i];
		break;
	}
}
```

in this method you convert _sPrinterName_ to lowercase but forget to convert _printerName_ so that if user set printer name without to convert lowercase your method does not find the printer

**Comment by MihailITPlace** [comment]
I faced this same problem. But I'm afraid that the author no longer supports this project.

**Comment by w3blogfr** [comment]
Hello, 
unfortunatly you're right.
I do not work anymore with Zebra printer, and I don't have the possibillity to test my changes anymore.

**Comment by MihailITPlace** [comment]
Hey! I have now checked the code similar to this on Zebra ZD410: 

```
PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
for (int i = 0; i < services.length; i++) {
        PrintServiceAttribute attr = services[i].getAttribute(PrinterName.class);
        sPrinterName = ((PrinterName) attr).getValue();
	if (sPrinterName.toLowerCase().indexOf(printerName.toLowerCase()) >= 0) {
	       psZebra = services[i];
		break;
	}
}
```

In my case, everything worked. I think these changes can be safely added to the maven repository. If you have the opportunity, of course. 

But I, unfortunately, do not understand why the printer is searched for by a substring, and not by a full match of names.
