### ISSUE TITLE
How can i implement the QR Code printing

### ISSUE THREAD

**Issue by raaj5671** [w3blogfr/zebra-zpl#9]
Hi,

I would like to know how can I implement the QR code printing.

Thanks.

**Comment by rlokanathan** [comment]
Thanks a lot for your quick reply.
I will work on it. 
Tq.

**Comment by baoyang23** [comment]
Can I convert pictures to ZPL and use this?

**Comment by w3blogfr** [comment]
No, you can convert pictures to ZPL, the libraries propose in the other way. You can write ZPL code, and have a preview

**Comment by baoyang23** [comment]
> No, you can convert pictures to ZPL, the libraries propose in the other way. You can write ZPL code, and have a preview

OK.Thanks.

**Comment by kailiangchen2020** [comment]
hi,can i convert zpl to image?

**Comment by w3blogfr** [comment]
You can obtain a image preview with that code

```
BufferedImage image = zebraLabel.getImagePreview();
ImageIO.write(image, "png", new File("zpl.graph"));
```

**Comment by kailiangchen2020** [comment]
Thanks for your reply.
The code you gave me has been tried before, but there seems to be something wrong with the setting of the ZebreLabel object, and I can't get the expected results.
the maven dependency is 
<dependency>
           <groupId>fr.w3blog</groupId>
          <artifactId>zebra-zpl</artifactId>
         <version>0.0.1</version>
 </dependency>
and my code is 
ZebraLabel zebraLabel = new ZebraLabel();
            zebraLabel.addElement(new ZebraText(zplCode));
            zebraLabel.setDefaultZebraFont(ZebraFont.ZEBRA_ZERO);
            zebraLabel.setWidthDots(1000);
            zebraLabel.setHeightDots(1000);
            zebraLabel.setDefaultZebraFont(ZebraFont.ZEBRA_ZERO);
            zebraLabel.setZebraPrintMode(ZebraPrintMode.CUTTER);

            BufferedImage image = zebraLabel.getImagePreview();

All I got is a orange block shape.
Looking forward to your reply
